title: Memorizable
description: >-
  Memorizable helps thousands of students to be better at vocabulary. We make things Memorizable.
baseurl: "/"
url: "https://memorizable-app.github.io/site"

# Build settings
plugins:
  - jekyll-feed

# Compile sass
sass:
   sass_dir: bower_components/bootstrap/scss

# Exclude from processing
exclude:
  - bower_components